"""add initial_ball to game_players

Revision ID: be884a1d933c
Revises: 169b451d6f2d
Create Date: 2023-11-30 04:12:20.991534

"""
from alembic import op
import sqlalchemy as sa



revision = 'be884a1d933c'
down_revision = '169b451d6f2d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_players', sa.Column('initial_ball', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_players', 'initial_ball')
    # ### end Alembic commands ###
