"""empty message

Revision ID: 97b9c3bced0d
Revises: 7a745e024c88
Create Date: 2024-01-15 02:49:19.577776

"""
from alembic import op
import sqlalchemy as sa



revision = '97b9c3bced0d'
down_revision = '7a745e024c88'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_networks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('neighbor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_players_game_id_fkey'),
    sa.ForeignKeyConstraint(['neighbor_id'], ['game_players.id'], name='game_players_neighbor_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['game_players.id'], name='game_players_player_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_networks')
    # ### end Alembic commands ###
