"""empty message

Revision ID: 01ebaae69a4f
Revises: 97b9c3bced0d
Create Date: 2024-02-04 22:18:53.481744

"""
from alembic import op
import sqlalchemy as sa



revision = '01ebaae69a4f'
down_revision = '97b9c3bced0d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_network_visible', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_network_visible')
    # ### end Alembic commands ###
