"""empty message

Revision ID: 7a745e024c88
Revises: e07d61e85a9d
Create Date: 2024-01-07 01:38:16.098549

"""
import sqlalchemy as sa
from alembic import op


revision = "7a745e024c88"
down_revision = "e07d61e85a9d"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games", sa.Column("winning_score", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "winning_score")
    # ### end Alembic commands ###
