"""empty message

Revision ID: 68e551f35b21
Revises: 42adb64fba4b
Create Date: 2024-03-09 16:17:14.130980

"""
from alembic import op
import sqlalchemy as sa



revision = '68e551f35b21'
down_revision = '42adb64fba4b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_groups',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('random_groups')
    # ### end Alembic commands ###
