"""add hashed_password

Revision ID: 42adb64fba4b
Revises: 01ebaae69a4f
Create Date: 2024-02-21 22:05:53.662615

"""
from alembic import op
import sqlalchemy as sa



revision = '42adb64fba4b'
down_revision = '01ebaae69a4f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
